name: myntra
description: 'A new Flutter project.'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

flutter_native_splash:
  image: assets/images/logo-big.png
  color: 'FFFFFF'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-Regular.ttf
          # weight: 500
        - asset: assets/fonts/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish-Italic.ttf
          style: italic
